package com.github.deianvn.pocketcalendar.styles

import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

val MONTH_WEEK_PADDING_H = 12.dp
val MONTH_WEEK_PADDING_H_SMALL = 4.dp

val MONTH_DAY_PADDING_TOP = 12.dp
val MONTH_DAY_PADDING_TOP_SMALL = 2.dp

val MONTH_DAY_PADDING_BOTTOM = 24.dp
val MONTH_DAY_PADDING_BOTTOM_SMALL = 3.dp

val MONTH_DAY_FONT_SIZE = 12.sp
val MONTH_DAY_FONT_SIZE_SMALL = 10.sp

val MONTH_DAY_SELECTED_OVAL_SIZE = 28.dp
val MONTH_DAY_SELECTED_OVAL_SIZE_SMALL = 15.dp

val MONTH_HEADER_FONT_SIZE = 15.sp
val MONTH_HEADER_FONT_SIZE_COMPACT = 17.sp

val MONTH_TITLE_PADDING_TOP = 12.dp
val MONTH_TITLE_PADDING_TOP_SMALL = 6.dp

val MONTH_TITLE_PADDING_BOTTOM = 4.dp
val MONTH_TITLE_PADDING_BOTTOM_SMALL = 2.dp

val MONTH_HEADER_PADDING_BOTTOM = 4.dp
val MONTH_HEADER_PADDING_BOTTOM_SMALL = 2.dp
